import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Risk Disclaimer",
  description: "Important risk disclosure for Market Heist AI.",
};

export default function RiskPage() {
  return (
    <article>
      <h1>Risk Disclaimer</h1>
      <p>Last updated: July 2026</p>

      <p>
        Market Heist AI provides <strong>educational market analysis and information only</strong>. It
        is <strong>not financial, investment, legal, or tax advice</strong>, and nothing on this
        platform should be interpreted as a recommendation to buy, sell, or hold any asset.
      </p>

      <h2>Trading involves substantial risk</h2>
      <ul>
        <li>Trading and investing in crypto, forex, and commodities carry a high level of risk and may not be suitable for everyone.</li>
        <li>You can lose some or all of your capital. Only trade with money you can afford to lose.</li>
        <li>Crypto assets are highly volatile and largely unregulated in many jurisdictions.</li>
      </ul>

      <h2>No guarantees</h2>
      <ul>
        <li>We do not guarantee any profit, outcome, accuracy, or performance.</li>
        <li>Signals are generated by an AI model and may be incomplete, delayed, or wrong.</li>
        <li>Past performance is not indicative of future results.</li>
      </ul>

      <h2>Your responsibility</h2>
      <p>
        You are solely responsible for your own decisions. Always do your own research and consider
        consulting a licensed financial professional before making any trading decision. By using
        Market Heist AI you acknowledge and accept these risks.
      </p>

      <p>
        Questions? Contact us at{" "}
        <a href="mailto:Info@marketheist.com">Info@marketheist.com</a>.
      </p>
    </article>
  );
}
